import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#08111F',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 120,
    gap: 24,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brand: {
    color: '#F8FAFC',
    fontSize: 28,
    fontWeight: '900',
  },
  brandSubcopy: {
    color: '#8FA5BF',
    marginTop: 4,
  },
  brandBadge: {
    backgroundColor: '#F97316',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  brandBadgeText: {
    color: '#FFF7ED',
    fontWeight: '800',
  },
  hero: {
    backgroundColor: '#0E1A2B',
    borderRadius: 28,
    padding: 24,
    gap: 14,
    borderWidth: 1,
    borderColor: '#1C2A3D',
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EAB308',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  heroBadgeText: {
    color: '#111827',
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  heroTitle: {
    color: '#F8FAFC',
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#A5B4C7',
    fontSize: 15,
    lineHeight: 22,
  },
  searchBox: {
    marginTop: 8,
    backgroundColor: '#F8FAFC',
    borderRadius: 20,
    padding: 8,
    gap: 8,
  },
  searchPanel: {
    backgroundColor: '#F8FAFC',
    borderRadius: 24,
    padding: 10,
  },
  searchInput: {
    backgroundColor: '#EFF3F8',
    color: '#0F172A',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
  },
  searchButton: {
    backgroundColor: '#F97316',
    borderRadius: 16,
    alignItems: 'center',
    paddingVertical: 14,
  },
  searchButtonText: {
    color: '#FFF7ED',
    fontWeight: '700',
    fontSize: 15,
  },
  secondaryButton: {
    backgroundColor: '#132235',
    borderRadius: 16,
    alignItems: 'center',
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#223451',
  },
  secondaryButtonText: {
    color: '#D8E6F7',
    fontWeight: '700',
    fontSize: 15,
  },
  dangerButton: {
    backgroundColor: '#7F1D1D',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#991B1B',
  },
  dangerButtonText: {
    color: '#FEE2E2',
    fontWeight: '700',
    fontSize: 15,
  },
  formCard: {
    backgroundColor: '#0E1A2B',
    borderRadius: 24,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: '#1C2A3D',
  },
  formLabel: {
    color: '#E5EEF9',
    fontWeight: '700',
    fontSize: 14,
  },
  materialHelperText: {
    color: '#8FA5BF',
    lineHeight: 20,
  },
  textArea: {
    minHeight: 96,
    backgroundColor: '#EFF3F8',
    color: '#0F172A',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    textAlignVertical: 'top',
  },
  helperCard: {
    backgroundColor: '#111827',
    borderRadius: 22,
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  helperBullet: {
    color: '#D8E6F7',
    lineHeight: 22,
  },
  updateCard: {
    backgroundColor: '#FFF7ED',
    borderRadius: 24,
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: '#FDBA74',
  },
  updateBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F97316',
    color: '#FFF7ED',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  updateTitle: {
    color: '#7C2D12',
    fontSize: 18,
    fontWeight: '800',
  },
  updateText: {
    color: '#9A3412',
    lineHeight: 21,
  },
  updateActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  updatePrimaryButton: {
    backgroundColor: '#F97316',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  updatePrimaryButtonText: {
    color: '#FFF7ED',
    fontWeight: '800',
  },
  updateDismissButton: {
    backgroundColor: '#FED7AA',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  updateDismissButtonText: {
    color: '#9A3412',
    fontWeight: '800',
  },
  dualButton: {
    flex: 1,
  },
  quickStatsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  itemActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  chip: {
    backgroundColor: '#132235',
    borderWidth: 1,
    borderColor: '#223451',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
  },
  chipActive: {
    backgroundColor: '#F97316',
    borderColor: '#F97316',
  },
  chipText: {
    color: '#C8D7E8',
    fontWeight: '700',
  },
  chipTextActive: {
    color: '#FFF7ED',
  },
  metricCard: {
    flex: 1,
    borderRadius: 22,
    padding: 18,
    minHeight: 110,
    justifyContent: 'flex-end',
  },
  metricBlue: {
    backgroundColor: '#172554',
  },
  metricOrange: {
    backgroundColor: '#7C2D12',
  },
  metricValue: {
    color: '#F8FAFC',
    fontSize: 28,
    fontWeight: '900',
  },
  metricLabel: {
    color: '#D9E4F5',
    marginTop: 6,
    lineHeight: 20,
  },
  section: {
    gap: 14,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#E5EEF9',
    fontSize: 21,
    fontWeight: '800',
  },
  sectionLink: {
    color: '#F59E0B',
    fontWeight: '700',
  },
  screenTitle: {
    color: '#F8FAFC',
    fontSize: 30,
    fontWeight: '900',
  },
  screenSubtitle: {
    color: '#93A6BC',
    lineHeight: 22,
  },
  highlightCard: {
    backgroundColor: '#122238',
    borderRadius: 24,
    padding: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#223451',
    gap: 8,
  },
  highlightGlow: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: '#1D4ED8',
    opacity: 0.14,
    top: -60,
    right: -40,
  },
  highlightType: {
    color: '#93C5FD',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  highlightTitle: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '800',
  },
  highlightMeta: {
    color: '#A9BAD0',
    lineHeight: 20,
  },
  discoveryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  discoveryCard: {
    width: '47%',
    minHeight: 112,
    backgroundColor: '#FFF7ED',
    borderRadius: 22,
    padding: 16,
    justifyContent: 'flex-end',
  },
  discoveryTitle: {
    color: '#7C2D12',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '800',
  },
  taskList: {
    backgroundColor: '#111827',
    borderRadius: 24,
    padding: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  taskCard: {
    backgroundColor: '#0E1A2B',
    borderRadius: 20,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: '#1C2A3D',
  },
  taskCardActive: {
    backgroundColor: '#162B45',
    borderColor: '#F97316',
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  taskBody: {
    flex: 1,
    gap: 4,
  },
  taskCheck: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#F97316',
  },
  taskText: {
    color: '#E5E7EB',
    fontSize: 15,
  },
  taskMeta: {
    color: '#8FA5BF',
    lineHeight: 18,
    fontSize: 12,
  },
  articleCard: {
    backgroundColor: '#122238',
    borderRadius: 22,
    padding: 18,
    gap: 8,
    borderWidth: 1,
    borderColor: '#20304A',
  },
  articleCardActive: {
    borderColor: '#F97316',
    backgroundColor: '#162B45',
  },
  articleCategory: {
    color: '#FDBA74',
    fontWeight: '800',
    textTransform: 'uppercase',
    fontSize: 12,
  },
  articleTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
  },
  articleDescription: {
    color: '#A8BCD3',
    lineHeight: 20,
  },
  articleMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  articleMetaPill: {
    backgroundColor: '#1D2D46',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  articleMetaText: {
    color: '#D6E3F3',
    fontSize: 12,
    fontWeight: '700',
  },
  recentSearchCard: {
    backgroundColor: '#0E1A2B',
    borderRadius: 22,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: '#1C2A3D',
  },
  recentSearchItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  recentSearchText: {
    color: '#E5EEF9',
    fontWeight: '700',
  },
  recentSearchCourse: {
    color: '#8FA5BF',
    fontSize: 12,
  },
  emptyState: {
    backgroundColor: '#111827',
    borderRadius: 22,
    padding: 20,
    gap: 8,
  },
  emptyTitle: {
    color: '#F8FAFC',
    fontWeight: '800',
    fontSize: 17,
  },
  emptyText: {
    color: '#94A3B8',
    lineHeight: 20,
  },
  sourceList: {
    gap: 12,
  },
  sourceItem: {
    backgroundColor: '#ECFDF5',
    borderRadius: 22,
    padding: 18,
  },
  sourceName: {
    color: '#134E4A',
    fontSize: 17,
    fontWeight: '800',
  },
  sourceType: {
    color: '#0F766E',
    marginTop: 4,
  },
  sourceSnippet: {
    color: '#14532D',
    marginTop: 10,
    lineHeight: 20,
  },
  agendaCard: {
    backgroundColor: '#ECFDF5',
    borderRadius: 24,
    padding: 18,
    gap: 12,
  },
  agendaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  agendaInfo: {
    flex: 1,
  },
  dayPill: {
    width: 46,
    backgroundColor: '#0F766E',
    paddingVertical: 8,
    borderRadius: 999,
    alignItems: 'center',
  },
  dayPillText: {
    color: '#F0FDFA',
    fontWeight: '800',
  },
  agendaText: {
    color: '#134E4A',
    fontWeight: '700',
  },
  agendaTime: {
    color: '#0F766E',
    marginTop: 4,
    fontWeight: '600',
  },
  planningCard: {
    backgroundColor: '#FFF7ED',
    borderRadius: 24,
    padding: 20,
    gap: 8,
  },
  planningTitle: {
    color: '#9A3412',
    fontWeight: '800',
    fontSize: 18,
  },
  planningText: {
    color: '#7C2D12',
    lineHeight: 22,
  },
  profileCard: {
    backgroundColor: '#1E293B',
    borderRadius: 28,
    padding: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileLabel: {
    color: '#FCD34D',
    fontWeight: '700',
    marginBottom: 6,
  },
  profileName: {
    color: '#F8FAFC',
    fontSize: 22,
    fontWeight: '800',
  },
  profileHandle: {
    color: '#94A3B8',
    marginTop: 4,
  },
  pointsBadge: {
    backgroundColor: '#F97316',
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 14,
    alignItems: 'center',
  },
  pointsValue: {
    color: '#FFF7ED',
    fontSize: 22,
    fontWeight: '900',
  },
  pointsLabel: {
    color: '#FED7AA',
    fontWeight: '700',
  },
  accountGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  accountCard: {
    width: '31%',
    backgroundColor: '#122238',
    borderRadius: 22,
    padding: 18,
    alignItems: 'center',
    gap: 6,
  },
  accountValue: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '900',
  },
  accountLabel: {
    color: '#94A3B8',
    textAlign: 'center',
  },
  toolList: {
    gap: 12,
  },
  materialCard: {
    backgroundColor: '#122238',
    borderRadius: 24,
    padding: 20,
    gap: 8,
    borderWidth: 1,
    borderColor: '#20304A',
  },
  materialMetaText: {
    color: '#A8BCD3',
    lineHeight: 20,
  },
  toolItem: {
    backgroundColor: '#111827',
    borderRadius: 24,
    padding: 20,
    gap: 8,
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  toolTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
  },
  toolText: {
    color: '#94A3B8',
    lineHeight: 21,
  },
  statusCard: {
    backgroundColor: '#0E1A2B',
    borderRadius: 18,
    padding: 16,
    gap: 6,
    borderWidth: 1,
    borderColor: '#1C2A3D',
  },
  statusTitle: {
    color: '#FCD34D',
    fontWeight: '800',
  },
  statusText: {
    color: '#CBD5E1',
    lineHeight: 20,
  },
  detailHero: {
    backgroundColor: '#122238',
    borderRadius: 28,
    padding: 24,
    gap: 12,
    borderWidth: 1,
    borderColor: '#20304A',
  },
  detailTitle: {
    color: '#F8FAFC',
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
  },
  detailDescription: {
    color: '#A8BCD3',
    lineHeight: 22,
    fontSize: 15,
  },
  detailBodyCard: {
    backgroundColor: '#111827',
    borderRadius: 24,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  detailBodyText: {
    color: '#D3DFEE',
    lineHeight: 24,
    fontSize: 15,
  },
  detailActions: {
    flexDirection: 'row',
    gap: 12,
  },
  backButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
  },
  backButtonText: {
    color: '#0F172A',
    fontWeight: '800',
  },
  savedSummaryCard: {
    backgroundColor: '#0E1A2B',
    borderRadius: 24,
    padding: 20,
    gap: 10,
    borderWidth: 1,
    borderColor: '#1C2A3D',
  },
  savedSummaryText: {
    color: '#D8E6F7',
    lineHeight: 22,
  },
  priorityPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#7C2D12',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  priorityText: {
    color: '#FFF7ED',
    fontSize: 12,
    fontWeight: '800',
  },
  calculatorCard: {
    backgroundColor: '#0E1A2B',
    borderRadius: 24,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: '#1C2A3D',
  },
  calculatorResult: {
    color: '#F8FAFC',
    fontSize: 28,
    fontWeight: '900',
  },
  calculatorHint: {
    color: '#93A6BC',
    lineHeight: 20,
  },
  assessmentCard: {
    flexDirection: 'row',
    backgroundColor: '#122238',
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#20304A',
  },
  assessmentCardActive: {
    backgroundColor: '#162B45',
    borderColor: '#F97316',
  },
  assessmentStripe: {
    width: 8,
  },
  assessmentBody: {
    flex: 1,
    padding: 18,
    gap: 4,
  },
  controlButton: {
    flex: 1,
    minWidth: 132,
  },
  compactControlButton: {
    flex: 1,
    minWidth: 110,
    paddingVertical: 10,
  },
  inlineInputs: {
    flexDirection: 'row',
    gap: 12,
  },
  miniInput: {
    flex: 1,
    backgroundColor: '#EFF3F8',
    color: '#0F172A',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
  },
  tabBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    backgroundColor: '#F8FAFC',
    borderRadius: 24,
    padding: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  tabItem: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
  },
  tabItemActive: {
    backgroundColor: '#0F172A',
  },
  tabText: {
    color: '#475569',
    fontWeight: '700',
  },
  tabTextActive: {
    color: '#F8FAFC',
  },
});
